### ISSUE TITLE
Filter cutoff frequencies still linear

### ISSUE THREAD

**Issue by SpacemanPaul** [attilammagyar/js80p#23]
#1 has been closed and the documentation says that logarithmic filter controls are "supported" but the actual controls are still linear.   Do I have to switch the filters into a logarithmic mode? How?  There is nothing in the docs.

**Comment by SpacemanPaul** [comment]
Nevermind, I've still got the old version installed somewhere else.

**Comment by attilammagyar** [comment]
I'm not sure I understand: are you saying that the little checkboxes above one or more cutoff frequency knobs are indicating logarithmic mode (ie. the checkbox has the blue light), but the knobs still behave linearly?

Btw. if you load a preset (or a DAW project) that was saved before #1 got implemented, then you will have to manually turn on log mode using the aforementioned checkboxes. If you create a new DAW project, then filter cutoffs will be in logarithmic mode by default (except for the 3 delay-based effects).

If your DAW made its own copy of the built-in presets, then you will have to tell it to refresh them, for example, in Reaper:

![image](https://github.com/attilammagyar/js80p/assets/364311/2b12444f-9ad0-43b3-8cc8-0c3285dd71d1)

The log mode switches are located right above the cutoff frequency knobs that they belong to:

![image](https://github.com/attilammagyar/js80p/assets/364311/f0ef9bec-7902-48dd-ba1f-624aa9034d4b)
![image](https://github.com/attilammagyar/js80p/assets/364311/2a938d07-29d1-4bb3-b054-838d2d77cf0a)

(Btw. I don't recommend older versions, they contain quite a few embarrassing bugs that have been fixed in newer versions. However, if you need them, you can still find all of them and their changelogs in [GitHub's archive](https://github.com/attilammagyar/js80p/releases).)

**Comment by attilammagyar** [comment]
Ah, sorry, I misunderstood the issue, now I realize that you were accidentally running a pre-v1.4.0 version thinking it was post-v1.4.0, and that's why it was linear.

My first interpretation was that it was a recent version that started behaving linearly (either due to a bug or due to an old or misconfigured patch), and that you reverted back to an older but still post-v1.4.0 version which worked correctly in your environment.

Sorry for the confusion.

**Comment by SpacemanPaul** [comment]
No problems.  It's working much better now than the last time I tried it.  I got some really gnarly sounds out of it.
