### ISSUE TITLE
download in chrome causes "suspicious download blocked" notification  

### ISSUE THREAD

**Issue by sdwarwick** [attilammagyar/js80p#27]
Something about the zip files in the releases causes "suspicious download blocked" message to show up in chrome browser.   is there something that would be easy to fix to prevent that?

**Comment by attilammagyar** [comment]
I cannot seem to be able to reproduce the issue: I can successfully download all of the ZIPs on Ubuntu Linux 22.04 with Google Chrome `119.0.6045.105 (Official Build) (64-bit)`, even with Safe Browsing set to the highest level ("Enhanced protection"). 

Google's [Safe Browsing site status page](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fattilammagyar.github.io%2Fjs80p%2F&hl=en) also reports the website as safe, and I get the same result for the [GitHub Releases page](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2Fattilammagyar%2Fjs80p%2Freleases%2Fdownload%2Fv2.4.1%2F&hl=en).

However, GitHub seems to serve the actual files from URLs like `https://objects.githubusercontent.com/github-production-release-asset-abcdef12345`, and the [Safe Browsing status of this](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fobjects.githubusercontent.com%2Fgithub-production-release-asset-2e65be%2F597908700%2F9c8162e8-b9c0-4a87-928b-657ec99ea495&hl=en) indicates that it doesn't know if the URL is safe due to "a lot of content" being associated with it.

1. What Chrome version are you using? Do I assume correctly (based on your previous issue, #22) that you're using Windows?
2. Does this problem occur with all files, or just specific ones, especially the FST (VST 2.4) ones which contain a `DLL` file?

**Comment by attilammagyar** [comment]
Well, maybe I don't see this warning because I tried it a few hours later.

Apparently other people run into the same problem from time to time, and [the theory in this comment from some Google support forum](https://support.google.com/webmasters/thread/110162617?hl=en&msgid=110169380) sounds plausible to me: 

> From https://support.google.com/chrome/answer/6261569
> 
> > Uncommon: You tried to download an unfamiliar and potentially dangerous piece of software.
> 
> People will get blocked, UNTIL Google has scanned it. Alas it is all very mysterious, on how to get Google to scan. 

Can you check if you still get the warning?

**Comment by sdwarwick** [comment]
happy to report that this problem resolved itself with an update to the latest chrome version: 119.0.6045.124

**Comment by attilammagyar** [comment]
I'm glad to hear that, thank you!
