### ISSUE TITLE
Knob labels unclear

### ISSUE THREAD

**Issue by SpacemanPaul** [attilammagyar/js80p#3]
The labels are extremely terse - a way to see the full parameter name without clicking on the modulation source would be very helpful.  Some sort of mouse-over "tool tip"?  Or display the full name of a knob currently being manually adjusted?

**Comment by attilammagyar** [comment]
The Windows version does have tooltips, but I didn't like those either, because they get quite annoying by always popping up at a place where they obscure something important (e.g. the parameter value that I'm trying to adjust).

That's why the next release (ETA: probably no longer than 2-3 days) will go with a different approach, that is already implemented in https://github.com/attilammagyar/js80p/commit/e82d4e1577b358201b452fa3614ea3ad4238a7b8
